-- MySQL Script generated by MySQL Workbench
-- Thu Aug  8 17:23:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyectofinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectofinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectofinal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyectofinal` ;

-- -----------------------------------------------------
-- Table `proyectofinal`.`colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectofinal`.`colaborador` (
  `idcolaborador` INT NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NULL DEFAULT NULL,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `nomusuario` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idcolaborador`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyectofinal`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectofinal`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nomrol` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyectofinal`.`colaborador_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectofinal`.`colaborador_rol` (
  `idcolaborador` INT NOT NULL,
  `idrol` INT NOT NULL,
  PRIMARY KEY (`idcolaborador`, `idrol`),
  INDEX `FKewl20srpb4ju1nqqfdxe52gwj` (`idrol` ASC) VISIBLE,
  CONSTRAINT `FK6i4gr39s63es9y711qkdvlxwh`
    FOREIGN KEY (`idcolaborador`)
    REFERENCES `proyectofinal`.`colaborador` (`idcolaborador`),
  CONSTRAINT `FKewl20srpb4ju1nqqfdxe52gwj`
    FOREIGN KEY (`idrol`)
    REFERENCES `proyectofinal`.`rol` (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
